const clientRouter      = require('./client')
const customFieldRouter = require('./customField')
const hmProductRouter   = require('./hmProduct')
const orderRouter       = require('./order')
const pictureRouter     = require('./picture')
const productRouter     = require('./product')
const reservationRouter = require('./reservation')
const storeRouter       = require('./store')
const textRouter        = require('./text')
const paypalRouter      = require('./paypal')

module.exports = app => {
  clientRouter(app)
  customFieldRouter(app)
  hmProductRouter(app)
  orderRouter(app)
  pictureRouter(app)
  productRouter(app)
  reservationRouter(app)
  storeRouter(app)
  textRouter(app)
  paypalRouter(app)
}