
export const SET_AUTH_TOKEN = 'SET_AUTH_TOKEN'

export const TOGGLE_DRAWER = 'TOGGLE_DRAWER'
export const CHANGE_DRAWER_OPEN = 'CHANGE_DRAWER_OPEN'

export const REQUEST_PRODUCTS = 'REQUEST_PRODUCTS'
export const RECEIVE_PRODUCTS = 'RECEIVE_PRODUCTS'
export const FAILED_REQUEST   = 'FAILED_REQUEST'
