/**************
 * AUTH TOKEN *
 **************/
export const SET_AUTH_TOKEN = 'SET_AUTH_TOKEN'

/************
 * PRODUCTS *
 ************/
export const ADD_PRODUCT    = 'ADD_PRODUCT'
export const REMOVE_PRODUCT = 'REMOVE_PRODUCT'
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT'

/**************
 * UI ACTIONS *
 **************/
export const CHANGE_DRAWER_OPEN    = 'CHANGE_DRAWER_OPEN'
export const CLOSE_ITEM_DIALOG     = 'CLOSE_ITEM_DIALOG'
export const CLOSE_SETTINGS_DIALOG = 'CLOSE_SETTINGS_DIALOG'
export const OPEN_ITEM_DIALOG      = 'OPEN_ITEM_DIALOG'
export const OPEN_SETTINGS_DIALOG  = 'OPEN_SETTINGS_DIALOG'
export const TOGGLE_DRAWER         = 'TOGGLE_DRAWER'

/***********
 * NETWORK *
 ***********/
export const REQUEST_CUSTOMFIELDS = 'REQUEST_CUSTOMFIELDS'
export const RECEIVE_CUSTOMFIELDS = 'RECEIVE_CUSTOMFIELDS'
export const REQUEST_HMPRODUCTS   = 'REQUEST_HMPRODUCTS'
export const RECEIVE_HMPRODUCTS   = 'RECEIVE_HMPRODUCTS'
export const REQUEST_ORDERS       = 'REQUEST_ORDERS'
export const RECEIVE_ORDERS       = 'RECEIVE_ORDERS'
export const REQUEST_PICTURES     = 'REQUEST_PICTURES'
export const RECEIVE_PICTURES     = 'RECEIVE_PICTURES'
export const REQUEST_PRODUCTS     = 'REQUEST_PRODUCTS'
export const RECEIVE_PRODUCTS     = 'RECEIVE_PRODUCTS'
export const REQUEST_RESERVATIONS = 'REQUEST_RESERVATIONS'
export const RECEIVE_RESERVATIONS = 'RECEIVE_RESERVATIONS'
export const REQUEST_STORES       = 'REQUEST_STORES'
export const RECEIVE_STORES       = 'RECEIVE_STORES'
export const REQUEST_TEXTS        = 'REQUEST_TEXTS'
export const RECEIVE_TEXTS        = 'RECEIVE_TEXTS'

export const FAILED_REQUEST   = 'FAILED_REQUEST'
export const FINISH_REQUEST   = 'FINISH_REQUEST'
export const START_REQUEST    = 'START_REQUEST'

